# Generated by Django 4.2.1 on 2023-05-10 13:26

import account.models_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userimage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=account.models_services.avatar_path, validators=[account.models_services.normal_avatar_size]),
        ),
    ]
