# Generated by Django 4.2.1 on 2023-05-11 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('df3e0bd2-095d-4b1d-a4fb-3aced2877744')),
        ),
    ]
