# Generated by Django 4.2.1 on 2023-05-22 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritemrelation',
            unique_together={('user', 'item')},
        ),
    ]
