# Generated by Django 4.2.1 on 2023-05-11 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
