version: '3.10'

services:
  web-backend:
    build: ./app
    command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    volumes:
      - ./app/:/usr/src/app
      - static_data:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpassword
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.25.0-alpine
    depends_on:
      - web-backend
    ports:
      - "80:80"
    volumes:
      - static:/app/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data:
  static_data:
