version: '3'

services:
  web-backend:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 absconfig.wsgi:application
    volumes:
      - .:/Ritem
      - static_data:/Ritem/static_cdn
    expose:
      - 8000
    depends_on:
      - database
    env_file: 
      - .env

  database:
    image: postgres:15-alpine
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25.0-alpine
    ports:
      - 80:80
    depends_on:
      - web-backend
    volumes:
      - static_data:/Ritem/static_cdn
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  static_data:
  postgres_data:
